import React from 'react'
import { ImCross } from 'react-icons/im'

function PrivacyScreen() {
    return (
        <div className="w-8/12 mx-auto  sm:py-36 flex justify-center items-center">

            <ul className="list-disc font-epilogue text-sm text-black">
                <span className="text-4xl font-semibold">Privacy Policy</span>
                <h3 className='text-xl  mt-2'>This Privacy Policy describes our policies and procedures on the collection, use and disclosure of your information when you use the services and determines your privacy rights and how the law protects you.</h3>
                <h3 className='text-xl mt-2'>We use your personal data to provide and improve the services. By using the services, you agree to the collection and use of information in accordance with this Privacy Policy. </h3>


                <h4 className='text-xl mt-10 font-semibold'>Interpretation and Definitions</h4>
                
                <h5 className='text-lg font-medium mt-2'>Interpretation</h5>
                <h6 className='text-lg'>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</h6>
                
                <h5 className='text-lg font-medium mt-2'>Definitions</h5>
                <h6 className='text-lg'>For the purpose of this Privacy Policy:</h6>
                <ul>
                    <li className='text-lg'>Account means a unique account created for you to access our services or parts of our services.</li>
                    <li className='text-lg'>Company (referred to as either "the Company", "We", "Us" or "Our" in this agreement) refers to RuDo wealth, United Arab Emirates.</li>
                    <li className='text-lg'>Cookies are small files that are placed on your computer, mobile device or any other device by a website, containing the details of your browsing history on that website among its many uses.</li>
                    <li className='text-lg'>Country refers to United Arab Emirates</li>
                    <li className='text-lg'>Device refers to any device that can access the website such as a computer, a cellphone or a digital tablet.</li>
                    <li className='text-lg'>Personal Data is any information that relates to an identified or identifiable individual.</li>
                    <li className='text-lg'>Service refers to the Website.</li>
                    <li className='text-lg'>Service Provider means any natural or legal person who processes the data on behalf of the company. It refers to third-party companies or individuals employed by the company to facilitate the services on behalf of the company, to perform services related to the website or to assist the company in analyzing how the services are being used.</li>
                    <li className='text-lg'>Usage Data refers to data collected automatically, either generated by the use of the website or from the website infrastructure itself (for example, the duration of a page visit).</li>
                    <li className='text-lg'>Website refers to RuDo wealth, accessible from https://rudowealth.com/</li>
                    <li className='text-lg'>You means the individual accessing or using the services, or the company website, or other legal entity on behalf of which such individual is accessing or using the website, as applicable.</li>
                </ul>


                <h4 className="text-xl font-semibold mt-5">Collecting and Using your Personal Data</h4>
                <h5 className='text-lg font-semibold mt-2'>Types of Data Collected</h5>


                <h5 className='text-lg'>Personal Data</h5>
                <h6>While using the website, we may ask you to provide certain personally identifiable information that can be used to contact or identify you. Personally identifiable information may include, but is not limited to:</h6>
                <ul>
                    <li className='text-lg'>Email address</li>
                    <li className='text-lg'>First name and last name</li>
                    <li className='text-lg'>Usage Data</li>
                </ul>

                <h5>Personal Data</h5>

            </ul>
        </div>
    )
}

export default PrivacyScreen
