import React from 'react'
import { ImCross } from 'react-icons/im'
import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'
import style from "./style.module.css"

let pr = `
# Interpretation and Definitions

## Interpretation

The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.

## Definitions

For the purpose of this Privacy Policy:

- Account means a unique account created for you to access our services or parts of our services.

- Company (referred to as either "the Company", "We", "Us" or "Our" in this agreement) refers to RuDo wealth, United Arab Emirates.

- Cookies are small files that are placed on your computer, mobile device or any other device by a website, containing the details of your browsing history on that website among its many uses.

- Country refers to United Arab Emirates

- Device refers to any device that can access the website such as a computer, a cellphone or a digital tablet.

- Personal Data is any information that relates to an identified or identifiable individual.

- Service refers to the Website.

- Service Provider means any natural or legal person who processes the data on behalf of the company. It refers to third-party companies or individuals employed by the company to facilitate the services on behalf of the company, to perform services related to the website or to assist the company in analyzing how the services are being used.

- Usage Data refers to data collected automatically, either generated by the use of the website or from the website infrastructure itself (for example, the duration of a page visit).

- Website refers to RuDo wealth, accessible from [https://rudowealth.com/](https://rudowealth.com/)

You means the individual accessing or using the services, or the company website, or other legal entity on behalf of which such individual is accessing or using the website, as applicable.

# Collecting and Using your Personal Data

## Types of Data Collected

### Personal Data

While using the website, we may ask you to provide certain personally identifiable information that can be used to contact or identify you. Personally identifiable information may include, but is not limited to:

-   Email address
    
-   First name and last name
    
-   Usage Data
    

### Usage Data

Usage Data is collected automatically when using the website.

Usage Data may include information such as your device's Internet Protocol address, browser type, browser version, the pages of our website that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.

When you access the website by or through a mobile device, we may collect certain information automatically, including, but not limited to, the type of mobile device you use, your mobile device unique ID, the IP address of your mobile device, your mobile operating system, the type of mobile Internet browser you use, unique device identifiers and other diagnostic data.

We may also collect information that your browser sends whenever you visit our website or when you access the website by or through a mobile device.

### Tracking Technologies and Cookies  
  

We use cookies and similar tracking technologies to track the activity on our website and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze our website. The technologies we use may include:

-   Cookies or Browser Cookies. A cookie is a small file placed on your device. you can instruct your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if you do not accept Cookies, you may not be able to use some parts of our website.
    
-   Flash Cookies. Certain features of our website may use local stored objects (or Flash Cookies) to collect and store information about your preferences or your activity on our website. Flash cookies are not managed by the same browser settings as those used for ‘Browser Cookies’.
    
-   Web Beacons. Certain sections of our website and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the company, for example, to count users who have visited those pages or opened an email and for other related website statistics.  
      
    

Cookies can be "Persistent" or "Session" cookies. Persistent cookies remain on your personal computer or mobile device when you go offline, while session cookies are deleted as soon as you close your web browser.

We use both session and persistent cookies for the purposes set out below:

- **Necessary / Essential Cookies**

- Type: Session Cookies

- Administered by: Us

- Purpose: These cookies are essential to provide you with services available through the website and to enable you to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these cookies, the services that you have asked for cannot be provided, and we only use these Cookies to provide you with best of services.

- **Cookie Policy / Notice Acceptance Cookies**

- Type: Persistent Cookies

- Administered by: Us

- Purpose: These cookies identify if users have accepted the use of cookies on the website.

- **Functionality Cookies**

- Type: Persistent Cookies

- Administered by: Us

- Purpose: These cookies allow us to remember choices you make when you use the website, such as remembering your login details or language preference. The purpose of these cookies is to provide you with a more personal experience and to avoid you having to re-enter your preferences every time you use the website.

## Use of your Personal Data

The Company may use personal data for the following purposes:

- To provide and maintain our website, including to monitor the usage of our website.

- To manage your account: to manage your registration as a user of the website. The personal data you provide can give you access to different functionalities of the website that are available to you as a registered user.

- For the performance of a contract: the development, compliance and undertaking of the purchase contract for the products, items or services you have purchased or of any other contract with us through the website.

- To contact you: To contact you by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.

- To provide you with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information.

- To manage your requests: To attend and manage your requests to us.

- For business transfers: We may use your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which personal data held by us about our website users is among the assets transferred.

- For other purposes: We may use your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our website, products, services, marketing and your experience.

We respect your privacy and therefore we will not share personal data to the third party to sell their products. It may be shared with our outsourced partner related to ongoing business requirements like our US broker, KYC partner etc.



We may also share your personal information in the following situations:

-   With Service Providers: We may share your personal information with Service Providers to monitor and analyze the use of our website, to contact you.
    
-   For business transfers: We may share or transfer your personal information in connection with, or during negotiations of any merger, sale of company assets, financing, or acquisition of all or a portion of our business to another company.
    
-   With Affiliates: We may share your information with our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include our parent company and any other subsidiaries, joint venture partners or other companies that we control or that are under common control with us.
    
-   With business partners: We may share your information with our business partners to offer you certain products, services or promotions.
    
-   With other users: when you share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside.
    
-   With your consent: We may disclose your personal information for any other purpose with your consent.
    

## Retention of your Personal Data

The company will retain your personal data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.

The Company will also retain usage data for internal analysis purposes. Usage data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of our services, or we are legally obligated to retain this data for longer time periods.

## Transfer of your Personal Data

Your information, including personal data is processed at the company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to and maintained on computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from your jurisdiction.

Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.

The Company will take all steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your personal data will take place to an organization or a country unless there are adequate controls in place including the security of your data and other personal information.

## Disclosure of your Personal Data

### Business Transactions

If the company is involved in a merger, acquisition or asset sale, your personal data may be transferred. We will provide notice before your personal data is transferred and becomes subject to a different Privacy Policy.

### Law enforcement

Under certain circumstances, the company may be required to disclose your personal data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).

### Other legal requirements

The company may disclose your Personal Data in the good faith belief that such action is necessary to:

-   Comply with a legal obligation
    
-   Protect and defend the rights or property of the company
    
-   Prevent or investigate possible wrongdoing in connection with the website
    
-   Protect the personal safety of users of the website or the public
    
-   Protect against legal liability
    

## Security of your Personal Data

The security of your personal data is important to us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your personal data, we cannot guarantee its absolute security.

# GDPR Data Protection Rights

We would like to make sure you are fully aware of all of your data protection rights. Every user is entitled to the following:

-   The right to access – you have the right to request copies of your personal data. We may charge you a small fee for this service.
    
-   The right to rectification – you have the right to request that we correct any information you believe is inaccurate. you also have the right to request that we complete the information you believe is incomplete.
    
-   The right to erasure – you have the right to request that we erase your personal data, under certain conditions.
    
-   The right to restrict processing – you have the right to request that we restrict the processing of your personal data, under certain conditions.
    
-   The right to object to processing – you have the right to object to our processing of your personal data, under certain conditions.
    
-   The right to data portability – you have the right to request that we transfer the data that we have collected to another organization, or directly to you, under certain conditions.
    

If you make a request, we have one month to respond to you. If you would like to exercise any of these rights, please contact us.

# Links to Other Websites

Our website may contain links to other websites that are not operated by us. If you click on a third party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit.

We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.

# CCPA Privacy Rights (Do Not Sell My Personal Information)

Under the CCPA, among other rights, California consumers have the right to:

-   Request that a business that collects a consumer’s personal data disclose the categories and specific pieces of personal data that a business has collected about consumers.
    
-   Request that a business deletes any personal data about the consumer that a business has collected.
    
-   Request that a business that sells a consumer’s personal data, not sell the consumer’s personal data.
    

If you make a request, we have one month to respond to you. If you would like to exercise any of these rights, please contact us.

  

# Children's Privacy

Our website does not address anyone under the age of 18. We do not knowingly collect personally identifiable information from anyone under the age of 18. If you are a parent or guardian and you are aware that your child has provided us with personal data, please contact us. If we become aware that we have collected personal data from anyone under the age of 18 without verification of parental consent, we take steps to remove that information from our servers.

If we need to rely on consent as a legal basis for processing your information and your country requires consent from a parent, we may require your parent's consent before we collect and use that information.

# Changes to this Privacy Policy

We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.

We will let you know via email and/or a prominent notice on our site, prior to the change becoming effective and update the "last updated" date at the top of this Privacy Policy.

You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.

# Contact Us

If you have any questions about this Privacy Policy, you can contact us at [Info@rudowealth.com](mailto:Info@rudowealth.com).
`

function LinkRenderer(props) {
    return (
        <a
            href={props.href}
            target="_blank"
            rel="noreferrer noopener"
            className=""
        >
            {props.children}
        </a>
    );
}
function HeadingRenderer(props) {
    return <h1 className="text-red sm:mt-10 mt-4 mb-3 font-semibold sm:text-3xl text-2xl">{props.children}</h1>;
}
function Heading2Renderer(props) {
    return <h2 className=" sm:mt-5 mt-3 mb-3 font-semibold sm:text-xl text-lg leading-tight">{props.children}</h2>;
}
function Heading3Renderer(props) {
    return <h3 className=" sm:mt-5 mt-2 mb-3 font-semibold sm:text-xl  leading-tight">{props.children}</h3>;
}
function paraRenderer(props) {
    return <p className="">{props.children}</p>;
}
function subtitleRenderer(props) {
    return <p className="font-semibold sm:mt-2 mt-3">{props.children}</p>;
}
function ulRenderer(props) {
    return <ul className="mt-2 list-disc ml-5">{props.children}</ul>;
}
function liRenderer(props) {
    return <li className="">{props.children}</li>;
}

const MarkdownRenderer = ({ children }) => {
    return (
        <ReactMarkdown
            className=""
            components={{
                a: LinkRenderer,
                h1: HeadingRenderer,
                h2: Heading2Renderer,
                h3: subtitleRenderer,
                p: paraRenderer,
                span: paraRenderer,
                ul: ulRenderer,

                li: liRenderer,
            }}
            remarkPlugins={[remarkGfm]}
        >
            {children}
        </ReactMarkdown>
    );
};


function PrivacyScreen({ children }) {
    return (
        <div className="sm:py-36 py-26 px-3 sm:w-11/12 max-w-screen-lg mx-auto">
            <h1 className='sm:text-5xl  text-red font-semibold text-3xl text-center pb-10'>
                Privacy Policy
            </h1>
            <h3 className='text-lg font-normal'>
                This Privacy Policy describes our policies and procedures on the collection, use and disclosure of your information when you use the services and determines your privacy rights and how the law protects you.
            </h3>
            <h3 className='text-lg font-normal'>
                We use your personal data to provide and improve the services. By using the services, you agree to the collection and use of information in accordance with this Privacy Policy.
            </h3>

            <div className='font-epilogue '>

                <MarkdownRenderer>{pr}</MarkdownRenderer>

            </div>

        </div>
    )
}

export default PrivacyScreen
